(in-package #:lilylink)

;;; Mapping from LilyPond post-event command names (and shorthand keywords)
;;; to MARK descriptors.  Each descriptor is (KIND XML-TAG . PROPS), where
;;; PROPS is an attribute plist (e.g. (:type "short")) possibly ending with a
;;; :text entry used for other-* marks.  KIND determines which MusicXML
;;; container the mark is emitted into.

(defconst +mark-commands+
  '((:accent . (:articulation "accent"))
    (:marcato . (:articulation "strong-accent"))
    (:staccato . (:articulation "staccato"))
    (:tenuto . (:articulation "tenuto"))
    (:staccatissimo . (:articulation "staccatissimo"))
    (:portato . (:articulation "detached-legato"))
    (:espressivo . (:other-articulation "other-articulation" :text "espressivo"))

    (:fermata . (:fermata "fermata"))
    (:shortfermata . (:fermata "fermata"))
    (:longfermata . (:fermata "fermata"))
    (:verylongfermata . (:fermata "fermata"))
    (:veryshortfermata . (:fermata "fermata"))
    (:henzeshortfermata . (:fermata "fermata"))
    (:henzelongfermata . (:fermata "fermata"))

    (:trill . (:ornament "trill-mark"))
    (:mordent . (:ornament "inverted-mordent"))
    (:prall . (:ornament "mordent"))
    (:turn . (:ornament "turn"))
    (:reverseturn . (:ornament "inverted-turn"))
    (:slashturn . (:ornament "turn" :slash "yes"))
    (:upmordent . (:other-ornament "other-ornament" :text "upmordent"))
    (:downmordent . (:other-ornament "other-ornament" :text "downmordent"))
    (:prallup . (:other-ornament "other-ornament" :text "prallup"))
    (:pralldown . (:other-ornament "other-ornament" :text "pralldown"))
    (:prallprall . (:other-ornament "other-ornament" :text "prallprall"))
    (:upprall . (:other-ornament "other-ornament" :text "upprall"))
    (:lineprall . (:other-ornament "other-ornament" :text "lineprall"))
    (:prallmordent . (:other-ornament "other-ornament" :text "prallmordent"))
    (:downprall . (:other-ornament "other-ornament" :text "downprall"))
    (:haydnturn . (:other-ornament "other-ornament" :text "haydnturn"))

    (:upbow . (:technical "up-bow"))
    (:downbow . (:technical "down-bow"))
    (:open . (:technical "open-string"))
    (:stopped . (:technical "stopped"))
    (:flageolet . (:technical "harmonic"))
    (:snappizzicato . (:technical "snap-pizzicato"))
    (:thumb . (:other-technical "other-technical" :text "thumb"))
    (:heel . (:other-technical "other-technical" :text "heel"))
    (:toe . (:other-technical "other-technical" :text "toe"))
    (:halfopen . (:other-technical "other-technical" :text "half-open"))
    (:vartoe . (:other-technical "other-technical" :text "var-toe"))
    (:varheel . (:other-technical "other-technical" :text "var-heel"))
    (:heelcircle . (:other-technical "other-technical" :text "heel-circle"))

    (:pppppp . (:dynamic "pppppp"))
    (:ppppp . (:dynamic "ppppp"))
    (:pppp . (:dynamic "pppp"))
    (:ppp . (:dynamic "ppp"))
    (:pp . (:dynamic "pp"))
    (:p . (:dynamic "p"))
    (:mp . (:dynamic "mp"))
    (:mf . (:dynamic "mf"))
    (:f . (:dynamic "f"))
    (:ff . (:dynamic "ff"))
    (:fff . (:dynamic "fff"))
    (:ffff . (:dynamic "ffff"))
    (:fffff . (:dynamic "fffff"))
    (:ffffff . (:dynamic "ffffff"))
    (:fp . (:dynamic "fp"))
    (:sf . (:dynamic "sf"))
    (:sff . (:other-dynamics "other-dynamics" :text "sff"))
    (:sp . (:other-dynamics "other-dynamics" :text "sp"))
    (:spp . (:other-dynamics "other-dynamics" :text "spp"))
    (:sfz . (:dynamic "sfz"))
    (:rfz . (:dynamic "rfz"))
    (:n . (:dynamic "n"))))

(defun lookup-mark (command)
  "Return the MARK descriptor (KIND XML-TAG . PROPS) for a LilyPond command
name keyword, or NIL if COMMAND is not an expressive mark."
  (assocdr command +mark-commands+))
